name: generate pacman game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    permissions:
      contents: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Deploy SVG to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          mkdir -p temp_out
          cp -r pacman-contribution-graph.svg temp_out/ 2>/dev/null || cp -r dist/pacman-contribution-graph.svg temp_out/ 2>/dev/null || true
          cp -r pacman-contribution-graph-dark.svg temp_out/ 2>/dev/null || cp -r dist/pacman-contribution-graph-dark.svg temp_out/ 2>/dev/null || true
          
          git checkout --orphan output
          git rm -rf .
          
          cp -r temp_out/* .
          rm -rf temp_out
          git add .
          git commit -m "Chore: Update Pac-Man contribution graph"
          git push origin output --force
